### ISSUE TITLE
Component Interface

### ISSUE THREAD

**Issue by anater** [juanparadox/react-tachyons#2]
Looking at the [wiki page](https://github.com/juanparadox/react-tachyons/wiki/Component-Interface) and wondering if we ought to hold the discussion here

**Comment by juanparadox** [comment]
We can have it here if it's easier!

**Comment by juanparadox** [comment]
Talking sizes:

What should the preset sizes be?
I am thinking that we should follow the "tachyons" way of naming the sizes, for example: xs, s, m, l, xl

I'm about to push a new sizing schema and want to know what you think about the different sizes and how they should be named.

**Comment by anater** [comment]
I dig that. One thing that's been really tough to figure out is how to apply new styles at different break points. Tachyons has prefixes for every value (ns, md, etc) but idk how we should apply it to a component 🤔

**Comment by juanparadox** [comment]
Maybe we pass it in as a "break" prop (or "breakpoint") and the user can pass in the values as the breakpoint class name and we just added it to the classes on the component.

**Comment by anater** [comment]
So, thinking about how we intend to use the thing, I disagree with my original thoughts on using breakpoints in props. Mainly because those breakpoints will be defined for the user when they import any [component](http://tachyons.io/components/). My thinking is we focus on reproducing that list of components that Tachyons maintainers have already put together. We should, of course, create reasonable sub components that somebody could use elsewhere (links, buttons, inputs, etc). But I think we focus on providing the bigger components to allow someone to quickly prototype with pre-defined components with simple interfaces. If they change a base component, then it could have repercussions throughout, but any props passed could prove to be good overrides. In any case, I think breakpoints would be an edge case.

For example, I'm designing an [article](http://tachyons.io/components/articles/title-highlight-header-cover/index.html) and I need a [header](http://tachyons.io/components/nav/logo-links-inline/index.html) and a [footer](http://tachyons.io/components/footers/studios/index.html). I'll want to change a few values (props) to change the design to what it should be. Consider this JSX:

```jsx
<div>
  <LogoLinksInlineNav
    logo="path/to/logo.ext"
    links= { someArrayOfLinks }
    bgColor="red"
    linkColor="white"
    linkUnderline={ true }
  />
  <TitleHighlightHeaderArticle
    headerColor="red"
    linkColor="red"
    linkColorOnHover="black"
    linkUnderline={ true }
  />
  <StudioFooter/>
</div>
```

The above component would have breakpoints build in. Manipulating breakpoints via props seems odd since you wouldn't provide any classNames on these components. It makes more sense for them to 'fork' the component for any custom break points and then they'll have the power of tachyons available to them in their new components.

**Comment by anater** [comment]
In short, let's provide things that are most likely to affect the design in a quick way, but for the things that would be faster to change with tachyons in className, let's leave that alone. Not unlike [rebass](http://jxnblk.com/rebass/), which is based on inline-styles.

**Comment by anater** [comment]
I've added a [mega list of components](https://github.com/juanparadox/react-tachyons/wiki/List-of-Components) to the wiki.

I prioritized them, but I think a lot of these can be condensed or skipped altogether. I figure we start with stuff that exists as HTML tags, then layout, and go from there using the _building blocks_.

**Comment by juanparadox** [comment]
Keeping in mind the interface you provided above and the mega list, if I were to jump in and create the "Large Paragraph" (LargeParagraph) component, where do the limits lie in terms of the available props? For example, The Tachyons html is like so:

```jsx
<main class="pa3 pa5-ns">
   <p class="f4 lh-copy measure">
     Typography has one plain duty before it and that is to convey information
     in writing. No argument or consideration can absolve typography from this
     duty. A printed work which cannot be read becomes a product without
     purpose.
   </p>
</main>
```

The interface, most simply, would be like so:
```jsx
<LargeParagraph
    text="Typography has one plain duty before it and that is to convey information
     in writing. No argument or consideration can absolve typography from this
     duty. A printed work which cannot be read becomes a product without
     purpose."
  />
```

So, how much customization do we give the user? Giving them too many props would urge the user to simply use HTML, but giving them too little would provide too many constraints and not enough flexibility.

**Comment by anater** [comment]
I'd always imagined the text to be passed as a child, so this component would be a wrapper. We should discuss some way of defining the mega list components ahead of time before building. For instance all the paragraph stuff falls under "Text". So perhaps it's a `<Text/>` component and the list items represent the different forms that component should be able to achieve.

```jsx

// Large Paragraph:
<Text lh="copy" f="4" measure>
  Typography has one plain duty before it and that is to convey information
   in writing. No argument or consideration can absolve typography from this
   duty. A printed work which cannot be read becomes a product without
   purpose.
</Text>

```

**Comment by anater** [comment]
```jsx

// Large Paragraph:
<Text
  lh="copy"
  f="4"
/>

```

**Comment by anater** [comment]
I do wonder about a `type` prop to tell it what type of text element to render (`<p>`, `<span>`, etc)

**Comment by juanparadox** [comment]
What would be the base styling for the Text component you mentioned above? The only reason I ask is because a Large Paragraph, according to Tachyons, is already "defined" by base styling that makes up the "Large Paragraph". If the user changes the styling that is "native" to that component, then it is no longer, in this case, a "Large Paragraph", according to Tachyons.

**Comment by anater** [comment]
~I guess it depends how composable we want it to be. I think the best answer would be that `<LargeParagraph/>` would pass its children into a `<Text/>` component with the configuration from above. In terms of the `<Text/>` render function:~

```jsx

<p className={ 
  `lh-${lh} f${f} ${ measure && 'measure' }`
}>
  { children }
</p>

```

Obviously this doesn't cover every case. May be worth discussing some offline.

**Comment by anater** [comment]
Scratched out the above after our offline discussion. key points:
1. Props should configure content only
2. In few cases (like Buttons) color configuration should be done with classNames to leverage Tachyons and not reinvent the wheel
3. Use placeholder content when no content props are provided.
