### ISSUE TITLE
When should isRequired be required?

### ISSUE THREAD

**Issue by juanparadox** [juanparadox/react-tachyons#27]
When setting the propTypes, when should isRequired be used: in what case?

I noticed that PR #18 included a handful of required, but since we have defaultProps, is this really needed? If we approach the problem from a prototyping point of view, the person using this to prototype may simply just want to use the default props values.

**Comment by anater** [comment]
I don't feel strongly about any being required, however, the point of doing it was to allow for scenarios where props are passed. In that case, I figured some ought to be required for it to display _properly_. All in all though, I agree with your point that (in the context of a prototyping tool) it isn't required. Requiring a field throws no error when defaultProps are used but when props are sent, it checks against them to be sure the component renders (properly).
