### ISSUE TITLE
Images are gone!

### ISSUE THREAD

**Issue by juanparadox** [juanparadox/react-tachyons#43]
It seems some of the img URLs that tachyons was using are no longer working and return a 400...

Do we have a preference on what to change the images to?

**Comment by anater** [comment]
I don't have a preference. There's tons of placeholder image apis. Placekitten would be cute.

**Comment by juanparadox** [comment]
First time I've heard of Placekitten... and I like it! I can go through and replace the images if you'd like.

**Comment by anater** [comment]
Sounds good!

**Comment by juanparadox** [comment]
False alarm with the images. It seems the previous URL's just simply need to be updated from 'mrmrs.io' to 'mrmrs.github.io'.
