### ISSUE TITLE
Layout components

### ISSUE THREAD

**Issue by anater** [juanparadox/react-tachyons#8]
- [x] Aspect Ratio
Aspect Ratio 16x9
Aspect Ratio 1x1
Aspect Ratio 3x4
Aspect Ratio 4x3
Aspect Ratio 4x6
Aspect Ratio 5x7
Aspect Ratio 5x8
Aspect Ratio 6x4
Aspect Ratio 7x5
Aspect Ratio 8x5
Aspect Ratio 9x16
- [x] Centered Container
- [x] Five Column
   - [ ] Five Column Collapse Alternate
   - [ ] Five Column Collapse Asymmetrical
   - [ ] Five Column Collapse Mixed
   - [ ] Five Column Collapse One
- [x] Four Column
   - [ ] Four Column Collapse Two Collapse One
   - [ ] Four Column Collapse Two
- [x] Three Column
   - [ ] Three Column Collapse One
- [x] Two Column
   - [ ] Two Column Collapse One
- [ ] Fixed Table Layout Grid
- [ ] Fixed Table Layout Grid Mixed Rows
- [x] Flag Object
   - [x] Flag Object Bottom
   - [x] Flag Object Collapse
   - [x] Flag Object Top
- [x] Full Screen Centered Title
- [x] Full Bleed 16x9
- [x] Full Bleed 4x6
- [x] Full Bleed 5x7
- [x] Full Bleed 5x8
- [x] Full Bleed 6x4
- [x] Full Bleed 7x5
- [x] Full Bleed 8x5
- [x] Full Bleed 9x16
- [x] Full Bleed Square
- ~Horizontal Aspect Ratios~

**Comment by anater** [comment]
@juanparadox we should discuss solutions for columns that collapse with odd numbers, as well as the table layout grid components. Those are more complex and I'm wondering if they're a bad fit for what we're trying to accomplish

**Comment by juanparadox** [comment]
@anater If the interface turns out to be a nightmare, not just to build but for the end-user, then yes, I agree that it may be a bad fit. We can talk this over offline and see if there is any compromise we can make. Those particular components can be left out and once we user test we can see if they still make sense for this project.
